{{/* Make sure all variables are set properly */}}
{{- include "tc.v1.common.loader.init" . }}

{{/* Render configmap for wireguard */}}
{{- $configmap := include "wg.env.configmap" . | fromYaml -}}
{{- if $configmap -}}
  {{- $_ := set .Values.configmap "wg-env-config" $configmap -}}
{{- end -}}

{{/* Copy config.serverPort to service */}}
{{- $_ := set .Values.service.main.ports.main "port" .Values.wg.serverPort -}}
{{/* This should never be changed by the user  */}}
{{- $_ := set .Values.service.main.ports.main "targetPort" "51820" -}}

{{/* Render the templates */}}
{{ include "tc.v1.common.loader.apply" . }}
